version: "3"
services:
 mongodb:
   image: mongo:latest
   container_name: "mongodb"
   ports:
     - 27017:27017
 vuttr:
   image: vuttr:1.0
   container_name: vuttr-mongodb
   environment:
     SPRING_PROFILES_ACTIVE: prod
   ports:
     - 3000:3000
   links:
     - mongodb
